[package]
name = "postgres-time-overflow"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
postgres = { version = "0.19", features = ["with-time-0_3", "with-chrono-0_4"] }
time = "0.3"
chrono = "0.4"
